// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetKeyBindings() {
  return window['go']['main']['App']['GetKeyBindings']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function OpenAudioFileDialog() {
  return window['go']['main']['App']['OpenAudioFileDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadAudioFile(arg1) {
  return window['go']['main']['App']['ReadAudioFile'](arg1);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function ResolveAction(arg1) {
  return window['go']['main']['App']['ResolveAction'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}

export function StartTerminalWithCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartTerminalWithCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateKeyBinding(arg1, arg2) {
  return window['go']['main']['App']['UpdateKeyBinding'](arg1, arg2);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
