// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetKeyBindings():Promise<Record<string, string>>;

export function GetVersionInfo():Promise<Record<string, string>>;

export function OpenAudioFileDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadAudioFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function ResolveAction(arg1:string):Promise<string>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;

export function StartTerminalWithCommand(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>,arg5:number,arg6:number):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateKeyBinding(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
